local_backend: true

backend:
  name: git-gateway

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "bands"
    label: "Ham Radio Bands"
    folder: "data/bands"
    create: true
    extension: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - label: "Wavelength"
        name: "wavelength"
        widget: "select"
        options: ["LF", "MF", "HF", "VHF", "UHF", "SHF"]
      - { label: "Lower Frequency",  name: "lower_frequency",  widget: "string" }
      - { label: "Upper Frequency",  name: "upper_frequency",  widget: "string" }

  - name: "manufacturers"
    label: "Manufacturers"
    folder: "data/manufacturers"
    create: true
    extension: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }

  - name: "modulations"
    label: "Modulations"
    folder: "data/modulations"
    create: true
    extension: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }

  - name: "antenna_connectors"
    label: "Antenna Connectors"
    folder: "data/antenna_connectors"
    create: true
    extension: "json"
    fields:
      - { name: "title", label: "Title", widget: "string" }

  - name: "radios"
    label: "Radios"
    label_singular: "Radio"
    folder: "data/radios"
    create: true
    extension: "json"
    fields:
      - { name: "title", label: "Model Name", widget: "string" }
      - { name: "mpn", label: "MPN", widget: "string", required: false }
      - { name: "rigreference_id", label: "RigReference ID", widget: "number" }
      - label: "Manufacturer"
        name: "manufacturer"
        widget: "relation"
        collection: "manufacturers"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - label: "Supported Bands"
        name: "supported_bands"
        widget: "relation"
        collection: "bands"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        multiple: true
      - { name: "memory_channels", label: "Memory Channels", widget: "number" }
      - { name: "memory_banks", label: "Memory Banks", widget: "number" }
      - label: "Frequency Ranges"
        label_singular: "Frequency Range"
        name: "frequency_ranges"
        widget: "list"
        fields:
          - { name: "tx", label: "TX supported", widget: "boolean", default: true }
          - { name: "lower", label: "Lower Frequency", widget: "number", hint: "in MHz e.g. 144" }
          - { name: "upper", label: "Upper Frequency", widget: "number", hint: "in MHz e.g. 148" }
      - label: "Modulations"
        name: "modulations"
        widget: "relation"
        collection: "modulations"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        multiple: true
      - name: "output_power"
        label: "Output Powers"
        label_singular: "Output Power"
        widget: "list"
        field: { name: "watt", label: "Watts", widget: "number", value_type: "float", step: 0.1 }
      - label: "Antenna Connector"
        name: "antenna_connector"
        widget: "relation"
        collection: "antenna_connectors"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
      - { name: "antenna_impedance_ohm", label: "Antenna Impedance (Î©)", widget: "number" }
      - { name: "operating_voltage", label: "Operating Voltage", widget: "number", value_type: "float", step: 0.1 }
      - { name: "battery_capacity_mah", label: "Battery Capacity (mAh)", widget: "number" }
      - label: "Dimensions"
        name: "dimensions"
        widget: "object"
        fields:
          - { name: "width", label: "Width", widget: "number", hint: "mm" }
          - { name: "height", label: "Height", widget: "number", hint: "mm" }
          - { name: "depth", label: "Depth", widget: "number", hint: "mm" }
      - { name: "weight", label: "Weight", widget: "number", hint: "grams" }
      - label: "Form Factor"
        name: "form_factor"
        widget: "select"
        options: ["Handheld", "Mobile", "Base", "Portable", "SDR", "Other"]
      - { name: "manufactured_start_year", label: "Manufactured Start Year", widget: "number", required: false }
      - { name: "manufactured_end_year", label: "Manufactured End Year", widget: "number", required: false }
      - { name: "manufactured_country", label: "Manufactured Country", widget: "string", required: false }